apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute2
  
  labels:
    app: compute2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compute2
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
      labels:
        app: compute2
    spec:
      containers:
      - name: compute
        image: hchetoui/compute:1.0
        ports:
        - containerPort: 8008